/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank.account;

import org.junit.Test;

import static org.junit.Assert.*;

public class WebAppTest {
    @Test
    public void testAppHasAGreeting() {
        WebApp classUnderTest = new WebApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
