/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank.account;

public class WebApp {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new WebApp().getGreeting());
    }
}
